version: "3.3"
services:
  app:  
    build:
      context: .
    environment:
      - GET_HOSTS_FROM=dns      
    ports:
      - "5000:5000"
    command: /bin/bash -c "sleep 200 && python -u /app/app.py" 

