version: "3.3"
services:
  app:  
    build:
      context: ./frontend
    environment:
      - GET_HOSTS_FROM=dns      
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    command: /bin/bash -c "sleep 200 && python -u /app/app.py" 

