version: "3.3"
services:
  pulsarbroker:
    hostname: pulsarbroker
    image: apachepulsar/pulsar-standalone
    ports:
      - "6650:6650"
    command: /pulsar/bin/pulsar standalone
    volumes:
      - $PWD/pulsario/:/home
    healthcheck:
      test: "curl -s --fail http://localhost:8080/admin/v2/brokers/health"



