version: "3.3"
services:
  pulsarbroker:
    hostname: pulsarbroker
    image: apachepulsar/pulsar:2.7.0
    ports:
      - "6650:6650"
      - "8080:8080"
    command: bin/pulsar standalone
  # dashboard:
  #   image: apachepulsar/pulsar-dashboard:2.7.0
  #   depends_on:
  #     - pulsarbroker
  #   ports:
  #     - "80:80"
  #   environment:
  #     - SERVICE_URL=http://pulsarbroker:8080
 
  producer:
    build: 
      context: ./producers
    depends_on:
      - pulsarbroker
    links:  
      - pulsarbroker:pulsarbroker
    restart: always
    volumes:
      - ./Producers:/app
    #command: /bin/bash -c "sleep 500000"
    command: /bin/sh -c "sleep 70 && python /app/producer_test.py"
    #entrypoint: /app/entrypoint.sh
    #command: /bin/bash -c "sleep 70 && python app/producer.py rai-prashanna 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"  
 app:
  build: ./frontend
  command: python -u app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
 db:
  image: mongo:latest
  hostname: test_mongodb
  environment:
    - MONGO_INITDB_DATABASE=q1
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
  volumes:
    - ./frontend/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
  ports:
    - 27017:27017
