version: "3.3"

networks:
  public:
    driver: overlay
    driver_opts:
      encrypted: 'true'
  private:
    driver: overlay
    driver_opts:
      encrypted: 'true'
    attachable: true
services:
  mongodb:
    image: mongo:latest
    networks:
      - private   
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    deploy:
      replicas: 2
    command: mongod  
    # deploy:
    #   replicas: 1

  mongo-express:
    image: mongo-express:latest
    networks:
      - public 
      - private  
    depends_on:
      - "mongodb"
    deploy:
      replicas: 1
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
    # deploy:
    #   replicas: 3


  pulsarbroker:
    hostname: pulsarbroker
    image: apachepulsar/pulsar-standalone
    networks:
      - private   
    ports:
      - "6650:6650"
      - "8080:8080"
    command: /pulsar/bin/pulsar standalone
    volumes:
      - $PWD/pulsario/:/home
    deploy:
      replicas: 1    
    healthcheck:
      test: "curl -s --fail http://localhost:8080/admin/v2/brokers/health"

  producer:
    build:
      context: ./producers
    depends_on:
      - pulsarbroker  
    volumes:
      - ./producers:/app
    deploy:
      replicas: 1
    command: /bin/bash -c "sleep 60 && python app/request-producer.py rai-prashanna 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"

  filter:
    build:
      context: ./filter
    depends_on:
      - pulsarbroker  
    volumes:
      - ./filter:/app
    deploy:
      replicas: 1
    command: /bin/bash -c "sleep 60 && python /app/filter.py"
  q1consumer:
    build:
      context: ./consumers
    depends_on:
      - pulsarbroker  
    volumes:
      - ./consumers:/app
    deploy:
      replicas: 1
    command: /bin/bash -c "sleep 60 && python /app/q1-consumer.py"
    #command: /bin/bash -c "sleep 2000000"
  q2consumer:
    build:
      context: ./consumers
    depends_on:
      - pulsarbroker  
    volumes:
      - ./consumers:/app
    #command: /bin/bash -c "sleep 2000000"
    deploy:
      replicas: 1
    command: /bin/bash -c "sleep 60 && python /app/q2-consumer.py 10"
    # deploy:
    #   replicas: 1
  q3consumer:
    build:
      context: ./consumers
    depends_on:
      - pulsarbroker  
    volumes:
      - ./consumers:/app
    deploy:
      replicas: 1
    command: /bin/bash -c "sleep 60 && python /app/q3-consumer.py"
    #command: /bin/bash -c "sleep 2000000"
  q4consumer:
    build:
     context: ./consumers
    depends_on:
      - pulsarbroker  
    volumes:
      - ./consumers:/app
    deploy:
      replicas: 1
    command: /bin/bash -c "sleep 60 && python /app/q4-consumer.py"
    #command: /bin/bash -c "sleep 2000000"
  aggregation:  
    image: patrick931024/g3-aggregation:v2
    depends_on:
      - pulsarbroker
    volumes:
      - ./aggregation:/app
    deploy:
      replicas: 1
    #command: /bin/bash -c "sleep 2000000"

