FROM python:3.9-buster
ADD requirements.txt q1-producer.py ./ 
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["./q1-producer.py", "timbolo6", "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"]
