version: "3.3"
services:
  q1consumer:
    build:
      context: .
    environment:
      - GET_HOSTS_FROM=dns
    command: /bin/bash -c "sleep 80 && python /app/q1-consumer.py"
  q2consumer:
    build:
      context: .
    environment:
      - GET_HOSTS_FROM=dns
    command: /bin/bash -c "sleep 80 && python /app/q2-consumer.py 10"

  q3consumer:
    build:
      context: .
    environment:
      - GET_HOSTS_FROM=dns
    command: /bin/bash -c "sleep 80 && python /app/q3-consumer.py"
  q4consumer:
    build:
     context: .
    environment:
      - GET_HOSTS_FROM=dns
    command: /bin/bash -c "sleep 80 && python /app/q4-consumer.py"
